databases:
- name: whatsfest
  databaseName: whatsfest
  user: whatsfest_user
  plan: free
  region: oregon
  ipAllowList:
  - source: 0.0.0.0/0
    description: everywhere
  postgresMajorVersion: "17"

services:
- type: web
  name: whatsfest-backend
  env: node
  plan: free
  buildCommand: cd backend && npm ci && npm run render-build
startCommand: cd backend && npm run render-start
  envVars:
  - key: NODE_ENV
    value: production
  - key: DATABASE_URL
    fromDatabase:
      name: whatsfest
      property: connectionString
  - key: ADMIN_KEY
    value: ChaveDeAcesso-festa17-J8kF%9zWp$rV3hL6sX
  - key: PORT
    value: 10000
  - key: FRONTEND_URL
    value: https://whatsfest.vercel.app