databases:
- name: whatsfest
  databaseName: whatsfest
  user: whatsfest_user
  plan: free
  region: oregon
  ipAllowList:
  - source: 0.0.0.0/0
    description: everywhere
  postgresMajorVersion: "17"

services:
- type: web
  name: whatsfest-backend
  env: node
  plan: free
  buildCommand: cd backend && npm ci && npm run build
  startCommand: cd backend && npm start
  envVars:
  - key: NODE_ENV
    value: production
  - key: DATABASE_URL
    fromDatabase:
      name: whatsfest
      property: connectionString
  - key: ADMIN_KEY
    generateValue: true
  - key: PORT
    value: 10000

- type: web
  name: whatsfest-frontend
  env: static
  plan: free
  buildCommand: cd frontend && npm ci && npm run build
  staticPublishPath: ./frontend/dist
  routes:
  - type: rewrite
    source: /*
    destination: /index.html
  envVars:
  - key: VITE_API_BASE_URL
    value: https://whatsfest-backend.onrender.com