services:
- type: web
  name: whatsfest-backend
  env: node
  plan: free
  buildCommand: cd backend && npm ci && npx prisma generate && npx prisma db push && npm run build
  startCommand: cd backend && npm start
  envVars:
  - key: NODE_ENV
    value: production
  - key: DATABASE_URL
    fromService:
      type: pserv
      name: dpg-d3fch6buibrs73dravp0-a
      property: connectionString
  - key: ADMIN_KEY
    value: ChaveDeAcesso-festa17-J8kF%9zWp$rV3hL6sX
  - key: PORT
    value: 10000
  - key: FRONTEND_URL
    value: https://whatsfest.vercel.app